language: ruby
rvm:
- 1.9.1
sudo: required
gemfile:
  - Gemfile
before_install:
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.1.0
  - gem install bundler
cache: bundler
branches:
  only:
    - master
